version: '3.8'
services:  
  database:
    container_name: accord_database
    image: mongo:4.4-bionic
    ports: [27017:27017]
    volumes: [/var/lib/mongodb:/data/db]
    restart: unless-stopped
  types:
    build: ./types
  backend:
    container_name: accord_backend
    depends_on: [types, database]
    build: ./backend
    ports: [3000:3000]
    env_file: [./backend/.env]
    volumes: [./backend:/app]
    entrypoint: npm run start:prod
    restart: unless-stopped
volumes:
  accord: