version: '3.8'
services:  
  database:
    container_name: accord_database
    image: mongo:4.4-bionic
    ports: [27018:27017]
    volumes: [accord:/data/db]
    restart: unless-stopped
  types:
    build: ./types
  backend:
    container_name: accord_backend
    depends_on: [types, database]
    build: ./backend
    ports: [3000:3000]
    env_file: [./backend/.env]
    volumes:
      - ./backend/src:/app/src
      - ./backend/assets:/app/assets
      - ./backend/logs:/app/logs
    entrypoint: npm run start:prod
    restart: unless-stopped
volumes:
  accord: