name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        mongodb-version: ['4.0', '4.2', '4.4']

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install packages for test
        run: npm ci
        working-directory: ./app
      - name: Test Backend
        run: npm test
        working-directory: ./app
        env:
          API_URL: http://localhost:3001/api
          EMAIL_ADDRESS: example@gmail.com
          EMAIL_PASSWORD: google_account_password
          MONGO_URI: mongodb://localhost/accord-test
          PORT: 3001
          ROOT_ENDPOINT: http://localhost:3001
          WEBSITE_URL: http://localhost:4200
