name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.2', '4.4']

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install Backend Packages
        run: npm ci
        working-directory: ./backend

      - name: Test Backend
        run: npm test
        working-directory: ./backend
        env:
          API_URL: http://localhost:3001/api
          EMAIL_ADDRESS: example@gmail.com
          EMAIL_PASSWORD: google_account_password
          MONGO_URI: mongodb://localhost/accord-test
          PORT: 3001
          ROOT_ENDPOINT: http://localhost:3001
          WEBSITE_URL: http://localhost:4200

      - name: Install Frontend Packages
        run: npm ci
        working-directory: ./frontend

      - name: Test Frontend
        uses: cypress-io/github-action@v2
        run: npm run e2e
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build:prod
        working-directory: ./frontend
