name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x, 17.x]
        mongodb-version: ['4.2', '4.4']

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install Backend Packages
        run: npm ci
        working-directory: ./backend

      - name: Test Backend
        run: npm test
        working-directory: ./backend
        env:
          MONGO_URI: mongodb://localhost/accord-test
          NODE_ENV: dev
          PORT: 3001
          WEBSITE_URL: http://localhost:4200

      - name: Install Frontend Packages
        run: npm i -f
        working-directory: ./frontend

      - name: Start Backend for Frontend e2e
        run: npm start &
        working-directory: ./backend
        env:
          MONGO_URI: mongodb://localhost/accord
          NODE_ENV: dev
          PORT: 3000
          WEBSITE_URL: http://localhost:4200

      # - name: Test Frontend
      #   uses: cypress-io/github-action@v2
      #   with:
      #     browser: chrome
      #     working-directory: ./frontend
      #     start: npm start

      - name: Build and Deploy Frontend
        run: npm run build:prod
        working-directory: ./frontend
